public with sharing class ExternalUserService {

    public static void handleNewUsers(Map<Id, User> mapUsers) {
        // Find permission set ids that should be assigned
          // Contact_Badge_Definition__mdt.getAll().values();

        // Create permission set assignments

        // Insert permission set assignments
          // Check for duplicates in future call with failed records
    }
    
}
